SPACESHIP_PROMPT_ORDER=(dir git node time char)
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIṔ_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_CHAR_COLOR_SUCCESS="green"
SPACESHIP_CHAR_COLOR_ERROR="red"
SPACESHIP_TIME_SHOW=true
SPACESHIP_TIME_FORMAT="%H:%M"
